version: 1.0.0+{build}

image:
  - Visual Studio 2022

configuration: Release

platform: x64

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

init:
  - ps: |
      dir
  - ps: |
      (Get-Content build-tdlib.ps1) | ForEach-Object {
              $_.Replace('$MSVC_HOME = "..\..\Microsoft Visual Studio\2022\Community"', '$MSVC_HOME = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"')
            } | Set-Content build-tdlib.ps1

      (Get-Content build-telegram-native.ps1) | ForEach-Object {
        $_.Replace('$MSVC_HOME = "..\..\Microsoft Visual Studio\2022\Community"', '$MSVC_HOME = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"')
      } | Set-Content build-telegram-native.ps1
      
build_script: 
  - ps: ./build-telegram-native.ps1
